#!/bin/sh
# igframe
# Fit an image into a specific ratio for Instagram.

VERSION="1.1.0"

igframe_main() {
	scriptpath="$( realpath "$0" )"
	scriptname="$( basename "$scriptpath" )"

	e_args=16

	[ -z "$BORDER" ] && BORDER=0
	[ -z "$COLOR" ] && COLOR=white

	ratio=square
	sharpen=0

	while getopts abBc:hlpstv opt
	do
		case $opt in
			a) sharpen=1 ;;
			b) BORDER=1 ;;
			B) BORDER=0 ;;
			c) COLOR="$OPTARG" ;;
			h) cmd=help ;;
			l) ratio=landscape ;;
			p) ratio=portrait ;;
			s) ratio=square ;;
			t) ratio=story ;;
			v) cmd=version ;;
			*) _invalid_opt ;;
		esac
	done

	shift $(( OPTIND - 1 ))

	[ -z "$cmd" ] && cmd="process"

	case "$cmd" in
		help|process|version) "igframe_$cmd" "$@" ;;
		*) _invalid_cmd ;;
	esac

	return $?
}

igframe_process() {
	[ $# -lt 1 ] && _fatal $e_args "Must specify input."

	input="$1"
	output="$2"

	if [ -z "$output" ]
	then
		extname="$( _extname "$input" )"
		output="$( basename "$input" "$extname" )-out$extname"
	fi

	border_size=0
	[ $BORDER -ne 0 ] && border_size=66

	out_w=1080

	case "$ratio" in
		landscape) out_h=810 ;;
		portrait) out_h=1350 ;;
		story) out_h=1920 ;;
		*) out_h=$out_w ;; # square
	esac

	sharpen_arg=
	[ $sharpen -ne 0 ] && sharpen_arg="-sharpen 0x2"

	magick \
		"$input" \
		-distort SRT 0 \
		-filter point \
		-thumbnail "$(( out_w - border_size ))x$(( out_h - border_size ))\>" \
		$sharpen_arg \
		-gravity center \
		-crop "${out_w}x${out_h}+0+0!" \
		-background "$COLOR" \
		-flatten \
		"$output" \
	;

	_echo "$output"
}

igframe_help() {
cat <<USAGE
$scriptname $VERSION

USAGE: $scriptname [<options>] <input> [<output>]

Fit an image into a specific ratio for Instagram.

If output name is not specified, the same name than the input will be used,
suffixed by '-out'.

OPTIONS:

	-a        Sharpen resized image.
	-b        Add border, or passe-partout, around picture.
	-B        Do not add border.
	-c        Specify background colour by name or hex value (e.g. #0011aa). Defaults to 'white'.
	-s        Use square ratio (1:1, 1080x1080). (Default.)
	-h        Show this help screen.
	-l        Use landscape ratio (4:3, 1080x810).
	-p        Use portrait ratio (4:5, 1080x1350).
	-t        Use story ratio (9:16, 1080x1920).
	-v        Show version.

USAGE
}

igframe_version() {
	_echo "$scriptname $VERSION"
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

_extname() {
	echo "$input" | sed -E 's/^[^\.]+//'
}

_fatal() {
	exit_code="$1"
	shift
	_error "$@"
	exit "$exit_code"
}

_invalid_cmd() {
	_error "Invalid command: $cmd"
	_echo
	igframe_usage
	exit $e_args
}

_invalid_opt() {
	_error "Invalid option: $opt"
	_echo
	igframe_usage
	exit $e_args
}

igframe_main "$@"
